services:
  app:
    container_name: GoPick-application
    build: ./shopping-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/gopick
    volumes:
      - ./shopping-app:/app
      - /app/node_modules

  mongodb:
    image: mongo:7
    container_name: GoPick-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
